const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('../models/Product');

dotenv.config();

const products = [
  {
    name: 'Ao Thun Basic Cotton',
    description: 'Ao thun cotton 100% form regular, mac hang ngay thoai mai.',
    price: 249000,
    originalPrice: 319000,
    category: 'Ao',
    images: ['https://picsum.photos/seed/ao-basic-1/900/1200', 'https://picsum.photos/seed/ao-basic-2/900/1200'],
    colors: ['Trang', 'Den', 'Xam'],
    sizes: ['S', 'M', 'L', 'XL'],
    countInStock: 45,
    badge: 'Hot',
  },
  {
    name: 'Ao So Mi Linen Tay Dai',
    description: 'Ao so mi linen thuan nhien, mem nhe va mat me.',
    price: 429000,
    originalPrice: 529000,
    category: 'Ao',
    images: ['https://picsum.photos/seed/somi-linen-1/900/1200', 'https://picsum.photos/seed/somi-linen-2/900/1200'],
    colors: ['Be', 'Xanh Navy'],
    sizes: ['M', 'L', 'XL'],
    countInStock: 28,
    badge: 'New',
  },
  {
    name: 'Ao Polo Theu Logo',
    description: 'Ao polo pique co gian nhe, co theu logo toi gian.',
    price: 389000,
    originalPrice: 469000,
    category: 'Ao',
    images: ['https://picsum.photos/seed/polo-logo-1/900/1200', 'https://picsum.photos/seed/polo-logo-2/900/1200'],
    colors: ['Trang', 'Xanh Reu'],
    sizes: ['S', 'M', 'L'],
    countInStock: 36,
    badge: 'Premium',
  },
  {
    name: 'Quan Jeans Slim Fit Xanh Dam',
    description: 'Quan jeans slim fit chat denim ben dep, de phoi do.',
    price: 559000,
    originalPrice: 699000,
    category: 'Quan',
    images: ['https://picsum.photos/seed/jeans-slim-1/900/1200', 'https://picsum.photos/seed/jeans-slim-2/900/1200'],
    colors: ['Xanh Dam'],
    sizes: ['29', '30', '31', '32', '33'],
    countInStock: 31,
    badge: 'Hot',
  },
  {
    name: 'Quan Kaki Ong Dung',
    description: 'Quan kaki ong dung phong cach smart-casual.',
    price: 499000,
    originalPrice: 599000,
    category: 'Quan',
    images: ['https://picsum.photos/seed/kaki-ongdung-1/900/1200', 'https://picsum.photos/seed/kaki-ongdung-2/900/1200'],
    colors: ['Kem', 'Nau'],
    sizes: ['30', '31', '32', '34'],
    countInStock: 26,
    badge: 'Sale',
  },
  {
    name: 'Quan Jogger Ni The Thao',
    description: 'Quan jogger ni mem, co gian 4 chieu cho van dong.',
    price: 329000,
    originalPrice: 419000,
    category: 'Quan',
    images: ['https://picsum.photos/seed/jogger-ni-1/900/1200', 'https://picsum.photos/seed/jogger-ni-2/900/1200'],
    colors: ['Den', 'Ghi'],
    sizes: ['M', 'L', 'XL'],
    countInStock: 50,
    badge: 'New',
  },
  {
    name: 'Vay Midi Hoa Nhi',
    description: 'Vay midi hoa nhi dang xoe nhe, phu hop di choi cuoi tuan.',
    price: 649000,
    originalPrice: 789000,
    category: 'Vay',
    images: ['https://picsum.photos/seed/vay-midi-1/900/1200', 'https://picsum.photos/seed/vay-midi-2/900/1200'],
    colors: ['Hong Pastel', 'Trang Kem'],
    sizes: ['S', 'M', 'L'],
    countInStock: 18,
    badge: 'New',
  },
  {
    name: 'Vay Bodycon Du Tiec',
    description: 'Vay bodycon ton dang voi chat lieu co gian vua phai.',
    price: 729000,
    originalPrice: 899000,
    category: 'Vay',
    images: ['https://picsum.photos/seed/vay-bodycon-1/900/1200', 'https://picsum.photos/seed/vay-bodycon-2/900/1200'],
    colors: ['Den', 'Do Do'],
    sizes: ['S', 'M'],
    countInStock: 14,
    badge: 'Premium',
  },
  {
    name: 'Chan Vay Xep Ly Ngan',
    description: 'Chan vay xep ly tre trung, de ket hop voi ao polo hoac so mi.',
    price: 379000,
    originalPrice: 469000,
    category: 'Chan vay',
    images: ['https://picsum.photos/seed/chanvay-ly-1/900/1200', 'https://picsum.photos/seed/chanvay-ly-2/900/1200'],
    colors: ['Den', 'Xam'],
    sizes: ['S', 'M', 'L'],
    countInStock: 24,
    badge: 'Hot',
  },
  {
    name: 'Ao Khoac Bomber Oversize',
    description: 'Ao khoac bomber oversize chong gio nhe, phoi streetwear dep.',
    price: 799000,
    originalPrice: 990000,
    category: 'Ao khoac',
    images: ['https://picsum.photos/seed/bomber-oversize-1/900/1200', 'https://picsum.photos/seed/bomber-oversize-2/900/1200'],
    colors: ['Den', 'Rau Cau'],
    sizes: ['M', 'L', 'XL'],
    countInStock: 16,
    badge: 'Premium',
  },
  {
    name: 'Ao Hoodie Fleece In Chu',
    description: 'Hoodie fleece day dan, giu am tot trong thoi tiet lanh.',
    price: 689000,
    originalPrice: 829000,
    category: 'Ao khoac',
    images: ['https://picsum.photos/seed/hoodie-fleece-1/900/1200', 'https://picsum.photos/seed/hoodie-fleece-2/900/1200'],
    colors: ['Xam Tro', 'Kem'],
    sizes: ['M', 'L', 'XL'],
    countInStock: 21,
    badge: 'Hot',
  },
  {
    name: 'Giay Sneaker Da Tron',
    description: 'Sneaker da trơn toi gian, de di hoc va di lam.',
    price: 890000,
    originalPrice: 1090000,
    category: 'Giay',
    images: ['https://picsum.photos/seed/sneaker-da-1/900/1200', 'https://picsum.photos/seed/sneaker-da-2/900/1200'],
    colors: ['Trang', 'Den'],
    sizes: ['39', '40', '41', '42', '43'],
    countInStock: 20,
    badge: 'Premium',
  },
  {
    name: 'Giay Loafer Da Mem',
    description: 'Giay loafer da mem, nhe chan, hop phong cach lich su.',
    price: 990000,
    originalPrice: 1190000,
    category: 'Giay',
    images: ['https://picsum.photos/seed/loafer-da-1/900/1200', 'https://picsum.photos/seed/loafer-da-2/900/1200'],
    colors: ['Nau', 'Den'],
    sizes: ['39', '40', '41', '42'],
    countInStock: 12,
    badge: 'New',
  },
  {
    name: 'Giay Running Mesh Nhe',
    description: 'Giay running than mesh thoang khi, de tap luyen hang ngay.',
    price: 759000,
    originalPrice: 920000,
    category: 'Giay',
    images: ['https://picsum.photos/seed/running-mesh-1/900/1200', 'https://picsum.photos/seed/running-mesh-2/900/1200'],
    colors: ['Xam', 'Xanh Duong'],
    sizes: ['40', '41', '42', '43', '44'],
    countInStock: 34,
    badge: 'Sale',
  },
  {
    name: 'Tui Tote Canvas In Chu',
    description: 'Tui tote canvas dung duoc nhieu do, thiet ke tre trung.',
    price: 229000,
    originalPrice: 299000,
    category: 'Phu kien',
    images: ['https://picsum.photos/seed/tote-canvas-1/900/1200', 'https://picsum.photos/seed/tote-canvas-2/900/1200'],
    colors: ['Kem', 'Den'],
    sizes: ['One Size'],
    countInStock: 60,
    badge: 'Hot',
  },
  {
    name: 'Mu Luoi Trai Classic',
    description: 'Mu luoi trai form dep, vai kaki chac chan.',
    price: 199000,
    originalPrice: 259000,
    category: 'Phu kien',
    images: ['https://picsum.photos/seed/mu-classic-1/900/1200', 'https://picsum.photos/seed/mu-classic-2/900/1200'],
    colors: ['Den', 'Xanh Navy', 'Trang'],
    sizes: ['One Size'],
    countInStock: 72,
    badge: 'New',
  },
  {
    name: 'That Lung Da Khoa Kim',
    description: 'That lung da tong hop, khoa kim loai ben dep.',
    price: 279000,
    originalPrice: 359000,
    category: 'Phu kien',
    images: ['https://picsum.photos/seed/thatlung-da-1/900/1200', 'https://picsum.photos/seed/thatlung-da-2/900/1200'],
    colors: ['Den', 'Nau Dam'],
    sizes: ['100', '110', '120'],
    countInStock: 40,
    badge: 'Sale',
  },
  {
    name: 'Bo Do The Thao 2 Mon',
    description: 'Set ao + quan chat lieu thoang mat cho hoat dong hang ngay.',
    price: 549000,
    originalPrice: 679000,
    category: 'Bo suu tap',
    images: ['https://picsum.photos/seed/set-thethao-1/900/1200', 'https://picsum.photos/seed/set-thethao-2/900/1200'],
    colors: ['Xanh Reu', 'Den'],
    sizes: ['M', 'L', 'XL'],
    countInStock: 22,
    badge: 'Hot',
  },
  {
    name: 'Do Ngu Satin Co Vien',
    description: 'Do ngu satin mem mat, thiet ke toi gian sang trong.',
    price: 459000,
    originalPrice: 569000,
    category: 'Do ngu',
    images: ['https://picsum.photos/seed/dongu-satin-1/900/1200', 'https://picsum.photos/seed/dongu-satin-2/900/1200'],
    colors: ['Hong Nude', 'Xanh Nhat'],
    sizes: ['S', 'M', 'L'],
    countInStock: 27,
    badge: 'New',
  },
  {
    name: 'Ao Len Cardigan Mong',
    description: 'Cardigan mong nhe, phoi layering dep cho mua thu.',
    price: 599000,
    originalPrice: 739000,
    category: 'Ao len',
    images: ['https://picsum.photos/seed/cardigan-mong-1/900/1200', 'https://picsum.photos/seed/cardigan-mong-2/900/1200'],
    colors: ['Be Sua', 'Nau Nhat'],
    sizes: ['M', 'L'],
    countInStock: 19,
    badge: 'Premium',
  },
];

async function seedProducts() {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    const operations = products.map((item) => ({
      updateOne: {
        filter: { name: item.name },
        update: { $set: item },
        upsert: true,
      },
    }));

    const result = await Product.bulkWrite(operations);
    console.log('Seed completed');
    console.log(`Matched: ${result.matchedCount}`);
    console.log(`Modified: ${result.modifiedCount}`);
    console.log(`Upserted: ${result.upsertedCount}`);
  } catch (error) {
    console.error('Seed failed:', error.message);
    process.exitCode = 1;
  } finally {
    await mongoose.disconnect();
  }
}

seedProducts();